# Site settings
title: I Want to Be Wrong
email: adam.lukens@mcpolemic.com
description: > # this means to ignore newlines until "baseurl:"
  Random musings on software and life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://McPolemic.github.io" # the base hostname & protocol for your site
twitter_username: McPolemic
github_username:  McPolemic

# Build settings
markdown: kramdown
