# This is a basic workflow to help you get started with Actions

name: New Weeknotes Post

# Controls when the workflow will run
on:
  # Run every Sunday at midnight UTC
  schedule:
    - cron: "0 0 * * SUN"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-weeknote:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Set up Git for committing
      - name: Set up git config
        run: |
          git config user.name "Adam Lukens"
          git config user.email "<adam.lukens@mcpolemic.com>"

      - name: Create and commit the new weeknotes
        run: |
          ./scripts/next_weeknotes_post.sh      
          git add .
          git commit -m "Add weeknotes post for $(date --iso-8601)"
          git push -u origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: new-weeknotes
          branch-suffix: timestamp
          title: Weeknotes
          assignees: "@McPolemic"
